volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:develop
    pull_policy: always
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: "root"
    env_file:
      - .env
    command: server standalone --worker-thread=128 --flow-path /tmp/kestra-flows
    volumes:
    #  - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ./flows:/tmp/kestra-flows
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          tutorial-flows:
            enabled: false
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/
          url: http://localhost:8080/
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started

  jikkou-server-api:
    container_name: jikkou_server_api
    ports:
      - "8085:8080"
    image: streamthoughts/jikkou-api-server:main
    environment:
      JIKKOU_CONFIGURATION: |
        micronaut:
          server:
            port: 8080
        jikkou:
          # The extension providers
          extension.providers:
            # By default, disable all extensions
            default.enabled: true
            # Explicitly enabled/disable extensions
            #<provider_name>.enabled: <boolean>
            core.enabled: true
            kafka.enabled: true
            kafka-connect.enabled: true
