apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: 'jikkou-demo-my-first-topic'
spec:
  partitions: 1
  replicas: 3
  configs:
    cleanup.policy: 'compact'
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: 'jikkou-demo-my-second-topic'
spec:
  partitions: 5
  replicas: 3
  configs:
    cleanup.policy: 'delete'
