apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: 'jikkou-demo-my-first-topic'
spec:
  partitions: 1
  replicas: 3
  configMapRefs:
    - TopicConfig
  configs:
    cleanup.policy: 'compact'
---
apiVersion: "kafka.jikkou.io/v1beta2"
kind: "KafkaTopic"
metadata:
  name: 'jikkou-demo-my-second-topic'
  annotations:
    jikkou.io/delete: true
spec:
  partitions: 5
  replicas: 3
  configMapRefs:
    - TopicConfig
  configs:
    cleanup.policy: 'delete'
---
apiVersion: "core.jikkou.io/v1beta2"
kind: "ConfigMap"
metadata:
  name: TopicConfig
data:
  retention.ms: 3600000
  max.message.bytes: 20971520
  min.insync.replicas: 1
